-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE "user"
(
    id serial NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    zipcode character(10),
    phone VARCHAR(10),
    avatar text,
    address text,
    is_active boolean DEFAULT '0',
    role_id integer NOT NULL,
    is_deleted boolean DEFAULT '0',
    created_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    created_by integer NOT NULL,
    modified_by integer NOT NULL,
    PRIMARY KEY (id),
	FOREIGN KEY (role_id) REFERENCES role (id),
	FOREIGN KEY (created_by) REFERENCES user(id),
	FOREIGN KEY (modified_by) REFERENCES user(id)
);

CREATE TABLE "role"
(
    id serial NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by integer NOT NULL,
    modified_by integer NOT NULL,
    PRIMARY KEY (id),
	FOREIGN KEY (created_by) REFERENCES user(id),
	FOREIGN KEY (modified_by) REFERENCES user(id)
);

CREATE TABLE "user_roles"
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    is_deleted bit(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.permission_list
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    is_deleted bit(1) DEFAULT 0,
    created_by integer NOT NULL,
    modified_by integer NOT NULL,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permission_access
(
    id serial,
    role_id integer,
    permission_id integer NOT NULL,
    can_view bit(1) DEFAULT 0,
    can_edit bit(1) DEFAULT 0,
    can_delete bit(1) DEFAULT 0
);

ALTER TABLE IF EXISTS public."user"
    ADD FOREIGN KEY (role_id, created_by, modified_by)
    REFERENCES public.role (id, id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role
    ADD FOREIGN KEY (created_by, modified_by)
    REFERENCES public."user" (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_roles
    ADD FOREIGN KEY (user_id, role_id)
    REFERENCES public."user" (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_roles
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.permission_list
    ADD FOREIGN KEY (created_by, modified_by)
    REFERENCES public."user" (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.permission_access
    ADD FOREIGN KEY (role_id, permission_id)
    REFERENCES public.role (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;